
name: 05-1 actitvity types

on:
    pull_request:
        types:
            - opened
            - synchronize
        branches:
            - main


jobs:
    echo:
        runs-on: ubuntu-latest
        steps:
            - run: echo "running whenever a PR is opned or synchronied and branch is main"

