
name: 05-2 actitvity types

on:
    pull_request:
        types:
            - closed
        branches:
            - main


jobs:
    echo:
        runs-on: ubuntu-latest
        steps:
            - run: echo "running whenever a PR is closed"
